# Generated by Django 4.0.4 on 2022-07-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_recipes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='recipes', through='food_recipes_app.RecipeIngredient', to='food_recipes_app.ingredient'),
        ),
    ]
